config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :films
  resources :comments
  resources :logs, only: [:index]
  get '/comments/:id/approve', to: 'comments#approve', as: :approve_comment
  root "films#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
  has_one :log
  validates :description , :film, presence: true
  validates :description , length: { in: 5..600}


  after_update  :criar_log
  def criar_log
    Log.create(comment_id: id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ap]
  before_action :set_films, only: %i[ new edit create update]


  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.status = false

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def approve
    @comment = Comment.find(params[:id])
    @comment.status = true
    respond_to do |format|
    if @comment.save
    format.html { redirect_to comments_url, notice: "Comentário aprovado com sucesso." }
    format.json { head :no_content }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @film.errors, status: :unprocessable_entity }
    end
   end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    private
    def set_films
      @films = Film.all.pluck(:title, :id)
    end


    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:description, :status, :film_id, :comment_id)
    end

    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Description:</strong>
    <%= comment.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= comment.status %>
  </p>

  <p>
    <strong>Film:</strong>
    <%= comment.film_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   
  <div>
    <%= form.label :film_title, 'Selecione o filme', style: "display: block" %>
    <%= form.select(:film_id, @films, {}, {}) %>
  </div>
  <div>
    <%= form.label :description, 'Comentário', style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/approve.html.erb
<h3>Aprova Comentário</h3>
<p><strong>ID:</strong> <%= @comment.id %></p>
<p><strong>Descrição:</strong> <%= @comment.description %></p>
<p><strong>Filme:</strong> <%= @comment.film.title %></>



app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<h3>Comentários não aprovados</h3>
<table>
  <thead>
    <tr>
      <th>Filme</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <% if comment.status == false %>
      <tr>
        <td><%= comment.film.title %></td>
        <td><%= comment.status%></td>
        <td><%= link_to "Ver Detalhe", comment %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "Cadastra novo comentário", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %> |
  <%= link_to "Aprova comentário", approve_comment_path(@comment) %> |

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>