config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :films
  resources :comments
  resources :logs, only: [:index]
  get '/comments/:id/approve', to: 'comments#approve', as: :approve_comment
  root "films#index"
end

app/models/film.rb
class Film < ApplicationRecord
    has_many :comments
    has_many :castfilms
    has_many :authors, through: :castfilms
    accepts_nested_attributes_for :castfilms

    
    validates :title , :releaseyear, presence: true
    validates :title, uniqueness: true, length: {maximum: 200}
    
    validates :releaseyear, 
    inclusion: { in: 1888..Date.today.year },
    format: { 
    with: /(19|20)\d{2}/i, 
    message: "deve ser um ano de quatro dígitos"
    }
    before_destroy :remove_film
    def remove_film
        Castfilm.where(film_id: id).destroy_all
    end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
    @film.castfilms.build
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    @startcount=1  
    @film.castfilms.each do |m|
      m.author_id = film_params[:castfilms_attributes]["0"][:author_id][@startcount]
      @startcount +=1
    end 
    respond_to do |format|
      if @film.save
        film_params[:castfilms_attributes]["0"][:author_id].drop(@startcount).each do |m|
          @film.castfilms.build(:author_id => film_params[:castfilms_attributes]["0"][:author_id][@startcount]).save
          @startcount += 1
      end
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:title, :releaseyear, castfilms_attributes: [author_id: [] ])
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Title:</strong>
    <%= film.title %>
  </p>

  <p>
    <strong>Releaseyear:</strong>
    <%= film.releaseyear %>
  </p>

</div>

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, 'Título', style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :releaseyear, 'Ano de lançamento', style: "display: block" %>
    <%= form.number_field :releaseyear %>
  </div>

  <div>
  <%= form.fields_for :castfilms do |ff| %>
    <%= ff.label :author_id %>
    <br>
    <%= ff.collection_check_boxes :author_id, Author.all, :id, :name,  {include_blank: true}, {:multiple => true, :class=>""} %>
  <% end %>
 </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<h3>Lista de Filmes</h3>
<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= link_to "|Detalhe sobre filme|", film %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "Cadastrar novo filme", new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @film %>
<h4> Autores: </h4>
<% @film.authors.each do |author| %>
      <p> <%= author.name %> </p>
<% end %>
<h4> Comentário: </h4>
<% @film.comments.each do |comment| %>
  <% if comment.status == true %>
      <p> <%= comment.description %> </p>
      <p>__________________________________<p>
  <% end %>
<% end %>

<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %> 
  <%= button_to "Destroy this film", @film, method: :delete %>
</div>