config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :films
  resources :comments
  resources :logs, only: [:index]
  get '/comments/:id/approve', to: 'comments#approve', as: :approve_comment
  root "films#index"
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :comment
  validates :comment, presence: true
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: %i[ show edit update destroy ]

  # GET /logs or /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1 or /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs or /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to log_url(@log), notice: "Log was successfully created." }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1 or /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to log_url(@log), notice: "Log was successfully updated." }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1 or /logs/1.json
  def destroy
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url, notice: "Log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.require(:log).permit(:date_comment, :comment_id)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date_comment, style: "display: block" %>
    <%= form.date_field :date_comment %>
  </div>

  <div>
    <%= form.label :comment_id, style: "display: block" %>
    <%= form.text_field :comment_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/_log.html.erb
<div id="<%= dom_id log %>">
  <p>
    <strong>Date comment:</strong>
    <%= log.date_comment %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= log.comment_id %>
  </p>

</div>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render "form", log: @log %>

<br>

<div>
  <%= link_to "Show this log", @log %> |
  <%= link_to "Back to logs", logs_path %>
</div>

app/views/logs/index.html.erb
<h3>Logs dos comentário aprovados</h3>
<table>
  <thead>
    <tr>
      <th>ID do comentário#</th>
      <th>data de aprovação</th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.comment_id %></td>
        <td><%= log.created_at%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render "form", log: @log %>

<br>

<div>
  <%= link_to "Back to logs", logs_path %>
</div>

app/views/logs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @log %>

<div>
  <%= link_to "Edit this log", edit_log_path(@log) %> |
  <%= link_to "Back to logs", logs_path %>

  <%= button_to "Destroy this log", @log, method: :delete %>
</div>